### ISSUE TITLE
XSS in Fileupload via filename

### ISSUE THREAD

**Issue by Hellow2019m** [Jemt/SitemagicCMS#103]
Affected version: v4.4.
Path:

```
 /SitemagicCMS/index.php?SMFilesUpload&SMExecMode=Dedicated&SMExt=SMFiles&SMFilesUploadPath=files/images&SMTemplateType=Basic
```

Post Payload: 

```
filename="xss<img src=1 onerror=alert(1)>"
```

![0314](https://user-images.githubusercontent.com/48396622/54365177-54f0df00-46a9-11e9-9fff-44d70954f38c.png)

![03141](https://user-images.githubusercontent.com/48396622/54365191-5a4e2980-46a9-11e9-93c8-fb265ec655e1.png)

**Comment by Jemt** [comment]
Thank you for reporting this. We are looking into it.

**Comment by Jemt** [comment]
Confirmed. Working on a fix.

**Comment by Jemt** [comment]
Sitemagic Cloud patched.

**Comment by Jemt** [comment]
Users of Sitemagic CMS are now prompted to update their website when logging in to the control panel.

@Hellow2019m Thank you for bringing this problem to our attention. Your work is very much appreciated, and thanks to you we can now make the web a little safer. Thanks! :-)
