### ISSUE TITLE
A problem with the new installation

### ISSUE THREAD

**Issue by aljailane** [Jemt/SitemagicCMS#130]
Hi, I am having trouble installing SitemagicCMS

 Note that I am doing a new installation on a subfolder but I only see the upgrade menu and the installation option does not appear

**Comment by Jemt** [comment]
This happens if you already have Sitemagic CMS installed (either fully or partially installed).
Please remove all files in the folder - leave only the web installer intact. Then run the installer in your browser.

**Comment by aljailane** [comment]
No, it is not installed before you install it for the first time

> This happens if you already have Sitemagic CMS installed (either fully or partially installed).
> Please remove all files in the folder - leave only the web installer intact. Then run the installer in your browser.

**Comment by Jemt** [comment]
Please post a screenshot of the folder contaning the web installer. It _only_ displays an Upgrade button if the file config.xml.php is present in the folder, and that file belongs to Sitemagic CMS, which indicates that Sitemagic CMS is already partially or fully installed.
