### ISSUE TITLE
Any ongoing process or further development .. ?

### ISSUE THREAD

**Issue by osworx** [Jemt/SitemagicCMS#150]
php 8.2 will be relased soon, but when I look into the code of SitemagicCMS I cannot see any developement (since years ..).
So it wonders me (and maybe other too) if there will be published a new (and better prepared [in terms of modern environement like php 8.x) version.

Additonal one note to the existing code base:
https://github.com/Jemt/SitemagicCMS/blob/564dd95934a394deda9dd09a61eedfdecf3bbce9/base/tables.sql#L5

is using latin charset, while it should be **utf8mb4_general_ci** to be able to support also other languages than English ;)

**Comment by Jemt** [comment]
Hi.
Sitemagic CMS does support unicode, although data is encoded using HEX entities which allows us to store it as Latin1.
Development has not been halted, but we are mainly supporting big companies still using Sitemagic CMS. For a brand new website I would suggest you take a look at alternative content management systems.
