### ISSUE TITLE
PHPMailer - Deprecated: __autoload() is deprecated

### ISSUE THREAD

**Issue by Jemt** [Jemt/SitemagicCMS#24]
On PHP 7.2.x users may see the following error:

Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /Users/jemt/www/SMCMS-JSShop/base/phpmailer/PHPMailerAutoload.php on line 45

See https://github.com/q2a/question2answer/issues/569 for details.

The problem arises because PHP detects that a deprecated __autoload function is present, and throws the warning even though the function is never called.

**Comment by Jemt** [comment]
Fixed with commit https://github.com/Jemt/SitemagicCMS/commit/2f814a4eca13b1328b05a99ea9cff60f42294394

**Comment by bigolho16** [comment]
dsadas

**Comment by bigolho16** [comment]
boa
