### ISSUE TITLE
PHP 7: Assume default value when ini_get returns false

### ISSUE THREAD

**Issue by Jemt** [Jemt/SitemagicCMS#3]
In SMDataSource.classes.php we have code such as
```
if (ini_get("mysql.max_links") !== "-1")
        throw new Exception("The number of MySQL connections allowed cannot be restricted (mysql.max_links)");
```
The code fails if ini_get(..) returns False. It should always assume the default value when False is returned.

http://php.net/manual/en/mysql.configuration.php

Problem initially reported on Facebook:
https://www.facebook.com/SitemagicCMS/posts/1644836868882246

**Comment by Tangol** [comment]
With the release of [PHP 7.2.0](http://php.net/) we should test the CMS using this version too (for future proofing).

**Comment by Jemt** [comment]
Fixed - closing issue.
