### ISSUE TITLE
Charset

### ISSUE THREAD

**Issue by Tangol** [Jemt/SitemagicCMS#5]
Right now, SitemagicCMS SQL uses `CHARACTER SET latin1 COLLATE latin1_swedish_ci;`

If you check the [Character Encodings Usage](https://w3techs.com/technologies/overview/character_encoding/all), you'll see that **latin** isn't used anymore.
The default now, is **UTF-8**, so we should convert to this.

Also, the `xml encoding="ISO-8859-1"` was replaced by **UTF-8**, so this should be changed too.

**Comment by Jemt** [comment]
Sitemagic CMS uses Latin1 / ISO-8859-1 which is native to PHP - we'll stick with that until PHP introduces native Unicode support. The use of mb_* functions is terrible and can hardly be considered acceptable for a modern programming language.

**Comment by Jemt** [comment]
Sitemagic CMS uses Latin1 / ISO-8859-1 which is native to PHP - we'll stick with that until PHP introduces native Unicode support. The use of mb_* functions is terrible and can hardly be considered acceptable for a modern programming language.
While we could change the encoding for XML documents and SQL, it would no change the internal encoding of Sitemagic CMS and PHP, hence serving no purpose.

**Comment by Tangol** [comment]
@Jemt I've suggested it on the principle of do it now, so you don't have to do it later (and you will have to do it later) - even [W3](https://validator.w3.org/nu/?doc=https%3A%2F%2Fsitemagic.org%2F) throws an warning, hence my other report [here](https://github.com/Jemt/SitemagicCMS/issues/6).

Also, everyone seems to have switched to it.
But then again, what do they know...
