### ISSUE TITLE
Code Optimisation

### ISSUE THREAD

**Issue by Tangol** [Jemt/SitemagicCMS#6]
While performing some tests on https://sitemagic.org/ I've found the following:

- https://validator.w3.org/nu/?doc=https%3A%2F%2Fsitemagic.org%2F
- https://gtmetrix.com/reports/sitemagic.org/Mv7eGMQr
- https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsitemagic.org%2F

As you can see, some tweaks are needed.
Thanks!

**Comment by Jemt** [comment]
Please do not report issues related to a website using Sitemagic CMS and please be more specific - just posting links is no good and nor is reporting multiple problems in the same ticket.

**Comment by Tangol** [comment]
All issues in the report are related to one thing, **code optimisation** (mostly HTML and JS).
I don't know what can be more specific than [this](https://validator.w3.org/nu/?doc=https%3A%2F%2Fsitemagic.org%2F), or [this](https://gtmetrix.com/reports/sitemagic.org/Mv7eGMQr)?
And with you knowing the code inside-out and by checking the results of the tests, you should know what to change/tweak in order to fix the warnings/errors. 

PS: the only way for me to scan for issues, was on a website that uses SitemagicCMS.
