### ISSUE TITLE
Code Analysis Tools

### ISSUE THREAD

**Issue by Tangol** [Jemt/SitemagicCMS#9]
Please note that you should add the following tools to the repository:
- https://scan.coverity.com/
- http://jshint.com/about/
- https://travis-ci.org/

These will help with code quality testing.

**Comment by Jemt** [comment]
Feel free to create a pull request :-)

**Comment by Tangol** [comment]
@Jemt With you being the **owner** of the project, you'll need to login with GitHub and and synchronize the SitemagicCMS Repository with the provided tools.
Then you can start scanning for defects.

I'm not able to create such a pull request.
